require('dotenv').config();
const db = require('./database');
async function migrate() {
  console.log('Running v2.1 new tables migration...');
  await db.raw('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
  await db.schema.createTableIfNotExists('school_settings', t => { t.uuid('id').primary().defaultTo(db.raw('uuid_generate_v4()')); t.uuid('school_id').references('id').inTable('schools').onDelete('CASCADE').unique(); t.string('school_name',255); t.text('address'); t.string('phone',30); t.string('email',255); t.string('website',255); t.string('logo_url',1000); t.string('primary_color',10).defaultTo('#0B1D35'); t.string('accent_color',10).defaultTo('#00C896'); t.string('motto',500); t.string('principal_name',255); t.string('principal_signature_url',1000); t.string('mpesa_paybill',30); t.string('bank_name',255); t.string('bank_account',50); t.string('bank_branch',255); t.string('at_sender_id',20).defaultTo('SHULE360'); t.jsonb('report_card_footer').defaultTo('{}'); t.timestamps(true,true); });
  await db.schema.createTableIfNotExists('invitation_tokens', t => { t.uuid('id').primary().defaultTo(db.raw('uuid_generate_v4()')); t.uuid('school_id').references('id').inTable('schools').onDelete('CASCADE'); t.string('token',64).notNullable().unique(); t.enum('role',['student','guardian','teacher','staff']).notNullable(); t.string('intended_name',255); t.string('intended_phone',20); t.string('intended_email',255); t.uuid('linked_student_id'); t.boolean('is_used').defaultTo(false); t.timestamp('used_at'); t.timestamp('expires_at'); t.uuid('created_by'); t.timestamps(true,true); });
  await db.schema.createTableIfNotExists('pending_accounts', t => { t.uuid('id').primary().defaultTo(db.raw('uuid_generate_v4()')); t.uuid('school_id').references('id').inTable('schools').onDelete('CASCADE'); t.string('full_name',255).notNullable(); t.string('email',255); t.string('phone',20); t.string('requested_role',50).notNullable(); t.string('password_hash',255).notNullable(); t.string('token_used',64); t.enum('status',['pending','approved','rejected']).defaultTo('pending'); t.uuid('reviewed_by'); t.timestamp('reviewed_at'); t.text('rejection_reason'); t.timestamps(true,true); });
  await db.schema.createTableIfNotExists('health_records', t => { t.uuid('id').primary().defaultTo(db.raw('uuid_generate_v4()')); t.uuid('school_id').references('id').inTable('schools').onDelete('CASCADE'); t.uuid('student_id').references('id').inTable('students').onDelete('CASCADE').unique(); t.string('blood_group',5); t.text('allergies'); t.text('chronic_conditions'); t.text('current_medications'); t.text('immunization_notes'); t.string('emergency_contact_name',255); t.string('emergency_contact_phone',20); t.string('personal_doctor',255); t.string('doctor_phone',20); t.string('nhif_number',50); t.text('special_needs'); t.timestamps(true,true); });
  await db.schema.createTableIfNotExists('infirmary_visits', t => { t.uuid('id').primary().defaultTo(db.raw('uuid_generate_v4()')); t.uuid('school_id').references('id').inTable('schools').onDelete('CASCADE'); t.uuid('student_id').references('id').inTable('students').onDelete('CASCADE'); t.uuid('nurse_id').references('id').inTable('staff'); t.timestamp('visit_time').notNullable().defaultTo(db.fn.now()); t.text('presenting_complaint').notNullable(); t.text('diagnosis'); t.text('medication_given'); t.text('dosage'); t.enum('outcome',['treated_returned','sent_home','referred_hospital','observation']).defaultTo('treated_returned'); t.boolean('parent_notified').defaultTo(false); t.timestamp('parent_notified_at'); t.text('nurse_notes'); t.timestamps(true,true); });
  await db.schema.createTableIfNotExists('library_resources', t => { t.uuid('id').primary().defaultTo(db.raw('uuid_generate_v4()')); t.uuid('school_id').references('id').inTable('schools').onDelete('CASCADE'); t.uuid('uploaded_by').references('id').inTable('staff'); t.string('title',255).notNullable(); t.text('description'); t.enum('resource_type',['pdf','video','document','image','link','audio']).notNullable(); t.enum('curriculum_mode',['eight_four_four','cbe','both']).defaultTo('both'); t.string('subject',100); t.string('grade_level',50); t.string('file_url',1000); t.string('thumbnail_url',1000); t.integer('file_size_kb'); t.integer('download_count').defaultTo(0); t.boolean('is_public').defaultTo(true); t.timestamps(true,true); });
  await db.schema.createTableIfNotExists('virtual_sessions', t => { t.uuid('id').primary().defaultTo(db.raw('uuid_generate_v4()')); t.uuid('school_id').references('id').inTable('schools').onDelete('CASCADE'); t.uuid('host_id').references('id').inTable('staff'); t.string('title',255).notNullable(); t.text('description'); t.enum('session_type',['lesson','staff_meeting','parent_meeting','revision']).defaultTo('lesson'); t.string('subject',100); t.string('grade_level',50); t.string('meeting_id',100); t.string('join_url',1000); t.timestamp('scheduled_at'); t.integer('duration_minutes').defaultTo(60); t.enum('status',['scheduled','live','ended','cancelled']).defaultTo('scheduled'); t.string('recording_url',1000); t.timestamp('recording_available_at'); t.integer('attendee_count').defaultTo(0); t.timestamps(true,true); });
  await db.schema.createTableIfNotExists('ai_exam_jobs', t => { t.uuid('id').primary().defaultTo(db.raw('uuid_generate_v4()')); t.uuid('school_id').references('id').inTable('schools').onDelete('CASCADE'); t.uuid('teacher_id').references('id').inTable('staff'); t.string('title',255).notNullable(); t.string('subject',100); t.string('grade_level',50); t.enum('exam_type',['cat','mock','end_of_term','assignment','revision']).defaultTo('cat'); t.enum('curriculum_mode',['eight_four_four','cbe']).defaultTo('eight_four_four'); t.integer('num_questions').defaultTo(20); t.string('source_file_url',1000); t.string('source_file_name',255); t.text('source_text'); t.jsonb('generated_questions').defaultTo('[]'); t.text('generated_pdf_url'); t.enum('status',['pending','processing','completed','failed']).defaultTo('pending'); t.text('error_message'); t.integer('term'); t.integer('academic_year'); t.timestamps(true,true); });
  await db.schema.createTableIfNotExists('bulk_upload_jobs', t => { t.uuid('id').primary().defaultTo(db.raw('uuid_generate_v4()')); t.uuid('school_id').references('id').inTable('schools').onDelete('CASCADE'); t.uuid('uploaded_by').references('id').inTable('staff'); t.enum('upload_type',['students','parents','staff']).notNullable(); t.string('file_url',1000); t.integer('total_rows').defaultTo(0); t.integer('processed').defaultTo(0); t.integer('success_count').defaultTo(0); t.integer('error_count').defaultTo(0); t.jsonb('errors').defaultTo('[]'); t.enum('status',['pending','processing','completed','failed']).defaultTo('pending'); t.boolean('sms_sent').defaultTo(false); t.timestamps(true,true); });
  await db.raw('CREATE INDEX IF NOT EXISTS idx_inv_tokens_school ON invitation_tokens(school_id, is_used)');
  await db.raw('CREATE INDEX IF NOT EXISTS idx_infirmary_student ON infirmary_visits(student_id, visit_time DESC)');
  await db.raw('CREATE INDEX IF NOT EXISTS idx_library_school ON library_resources(school_id, curriculum_mode)');
  await db.raw('CREATE INDEX IF NOT EXISTS idx_virtual_school ON virtual_sessions(school_id, status)');
  console.log('v2.1 migration complete — 8 new tables created.');
  await db.destroy();
}
migrate().catch(err => { console.error('Migration failed:', err); process.exit(1); });
